site_name: "AWS Lake Formation Best Practices Guides"
repo_name: "aws/aws-lakeformation-best-practices"
repo_url: "https://github.com/aws/aws-lakeformation-best-practices"
docs_dir: "content"
theme:
  name: material
  features:
    - tabs
    - content.code.copy
    - content.code.select
    - content.code.copy
    - content.code.select
nav:
  - Introduction: 'index.md'
  - 'Adopting Lake Formation':
    - 'Overview': 'adopting-lake-formation/overview.md'
    - 'Considerations when adopting Lake Formation': 'adopting-lake-formation/considerations-when-adopting-lake-formation.md'
    - 'Lake formation Adoption Modes': 'adopting-lake-formation/lake-formation-adoption-modes.md'
    - 'General Best Practices': 'adopting-lake-formation/general-best-practices.md'
  - 'Data Sharing':
    - 'Overview': 'data-sharing/overview.md'
    - 'General Best Practices when using Lake Formation Data Sharing': 'data-sharing/general-data-sharing.md'
    - 'Cross Account Versions': 'data-sharing/cross-account-versions.md'
    - 'Upgrading Cross Account Version': 'data-sharing/upgrading-cross-account-versions.md'
    - 'Cross Account FAQS': 'data-sharing/cross-account-faq.md'
  - 'LF-Tags':
    - 'Overview': 'lf-tags/overview.md'
    - 'LF-Tags Basics': 'lf-tags/basics.md'
    - 'Common Ontologies': 'lf-tags/common-ontologies.md'
    - 'Developing an LF-Tag Ontology': 'lf-tags/developing-an-lftag-ontology.md'
    - 'Best Practices': 'lf-tags/best-practices.md'
    - 'Example Usecase': 'lf-tags/example-usecase.md'
    - 'Limitations': 'lf-tags/limitations.md'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - sane_lists
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - sane_lists
  - tables