site_name: "AWS Lake Formation Best Practices Guides"
repo_name: "aws/aws-lake-formation-best-practices"
repo_url: "https://github.com/aws/aws-lake-formation-best-practices"
docs_dir: "content"
theme:
  name: material
  features:
    - tabs
nav:
  - Introduction: 'index.md'
  - 1. LF-Tags:
      - LF-Tag Basics: 'lf-tags/basics.md'
      - Common Ontologies: 'lf-tags/common-ontologies.md'
      - Best Practices: 'lf-tags/best-practices.md'
      - Limitations: 'lf-tags/limitations.md'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite