site_name: "AWS Lake Formation Best Practices Guides"
repo_name: "aws/aws-lakeformation-best-practices"
repo_url: "https://github.com/aws/aws-lakeformation-best-practices"
docs_dir: "content"
theme:
  name: material
  features:
    - tabs
    - content.code.copy
    - content.code.select
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - sane_lists
  - tables